name: Tombamento Develop -> Release (Reset Total)

description: 'Reset total da branch release'

inputs:
  develop-branch:
    description: 'Nome da branch de desenvolvimento'
    required: true
  release-branch:
    description: 'Nome da branch de release'
    required: true
  github-token:
   required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repositório
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.github-token }}

    - name: Configurar Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Tombamento develop -> release
      run: |
        DATE=$(date +'%Y.%m.%d')
        git fetch origin ${inputs.develop-branch}
        git fetch origin ${inputs.develop-branch}
        git pull origin ${inputs.develop-branch}
        git fetch origin ${inputs.release-branch}
        git checkout ${inputs.release-branch}
        git pull origin ${inputs.release-branch}
        git reset --hard origin ${inputs.develop-branch}
        git add .
        git commit -m "Tobamento total da branch develop para release em $DATE"
        git push origin ${inputs.release-branch} --force

    - name: Criar tag de release
      run: |
        DATE=$(date +'%Y.%m.%d')
        git tag -a "release-$DATE" -m "Release quinzenal (reset develop -> release em $DATE)"
        git push origin "release-$DATE"