name: Meu Workflow

on:
  schedule:
    - cron: "0 9 1,15 * *"   # roda a cada 15 dias
  workflow_dispatch:         # execução manual
  push:
    branches: ["develop"]

jobs:
  meu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Tombamento Develop -> Release
        uses: .\.github\actions\tombamento
        with:
          develop-branch: 'develop'
          release-branch: 'release'
          github-token: ${{ secrets.GITHUB_TOKEN }}